### ISSUE TITLE
Add environment variables to github repo for publishing jars under `com.github.sbt`

### ISSUE THREAD

**Issue by mdedetrich** [sbt/sbt-pull-request-validator#11]
@eed3si9n  If this is already done then just feel free to close ticket

**Comment by eed3si9n** [comment]
Yea I've put in the Sonatype creds already.

**Comment by mkurz** [comment]
> Yea I've put in the Sonatype creds already.

In addition I just added Play's `PGP_SECRET` and `PGP_PASSPHRASE` for signing. We should be good to go now.
@mdedetrich If you provide the next PRs we can get this out today hopefully.

**Comment by mdedetrich** [comment]
> > Yea I've put in the Sonatype creds already.
> 
> In addition I just added Play's `PGP_SECRET` and `PGP_PASSPHRASE` for signing. We should be good to go now.


It would probably be more ideal to set up a key that's specific for sbt community plugins which all of the plugins can use.

It's not that critical though since no one really checks this (at most people check that it's signed or not but it stops there)
