### ISSUE TITLE
Travis CI dropped

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt-pull-request-validator#5]
Given the poor handling of the recent security incident (https://arstechnica.com/information-technology/2021/09/travis-ci-flaw-exposed-secrets-for-thousands-of-open-source-projects/) I'm suspending Travis CI integration indefinitely.

Let's move on to GitHub Actions.

**Comment by mkurz** [comment]
@eed3si9n If you
* add the `sbt-web` to this repo (https://github.com/sbt/sbt-pull-request-validator/settings/access) and 
* add `SONATYPE_USERNAME` and `SONATYPE_PASSWORD` secrects (https://github.com/sbt/sbt-pull-request-validator/settings/secrets/actions)

I can set up sbt-ci-release and publish this plugin to `com.github.sbt`.

**Comment by mkurz** [comment]
@mdedetrich @pjfanning you might be interested that this plugin is used in Pekko [here](https://github.com/apache/incubator-pekko/blob/v1.1.0-M0/project/plugins.sbt#L26) and, according to my research, is the last sbt plugin Pekko is using that is _not_ hosted on maven central (yet): https://repo1.maven.org/maven2/com/hpe/

**Comment by mkurz** [comment]
@eed3si9n @mdedetrich @pjfanning The question is should we keep this plugin under the `com.hpe.sbt` groupId (which we would need credentials for to publish to) or switch `com.github.sbt`?

**Comment by eed3si9n** [comment]
I highly doubt that HP Enterprise would let us publish JARs to Maven Central. /cc @2m

**Comment by eed3si9n** [comment]
@mkurz sbt-web team now has the Admin rights to this repo, and I've put in the creds.

**Comment by mkurz** [comment]
> @mkurz sbt-web team now has the Admin rights to this repo, and I've put in the creds.

Great, I will make the switch to `com.github.sbt` then.

**Comment by mdedetrich** [comment]
@eed3si9n If you wan't to give my rights as well then go ahead, I will also help with @mkurz to get this project up to scratch

**Comment by eed3si9n** [comment]
@mdedetrich Added you to https://github.com/orgs/sbt/teams/sbt-pull-request-validator team.

**Comment by mkurz** [comment]
We should not forget to 

- [ ] let scala steward know about the new groupId

**Comment by mkurz** [comment]
Just to let you know I already created a PR for scala-steward for the groupId switch:
- https://github.com/scala-steward-org/scala-steward/pull/3274

**Comment by mdedetrich** [comment]
@mkurz So from what I can tell everyone has been setup for the project to be ready for a release. There may be additional changes needed but the project is in a state when it can be worked on normally now anyways

**Comment by mkurz** [comment]
@mdedetrich So lets release. I think you should be able to push a tag.

**Comment by mkurz** [comment]
@mdedetrich I see you just published https://github.com/sbt/sbt-pull-request-validator/releases/tag/v2.0.0, however [the regarding workflow](https://github.com/sbt/sbt-pull-request-validator/actions/runs/7681336394) did not finish yet. Even when GitHub actions is done and artifacts got uploaded it will take another ~20 minutes for the artifacts to be available (I had cases where it took up to 2 hours). 
I would not publish the release notes before I am sure that the release is actually downloadable from maven central... specially the workflow can hang, there can be config problems (like to forget to set the correct sonatype profile name for sbt-ci-release, etc.).
So it _could_ happen 2.0.0 never makes it... But people watching this repo (even just for releases) get notified about a release that maybe never is available.
Just my 2 cents, since I did the same in the past, but now always verify the release and only then publish the GitHub release which pushed out notifications.
(I don't want to be the smart guy here, just sharing my experience)

**Comment by mdedetrich** [comment]
> (I don't want to be the smart guy here, just sharing my experience)

No worries, no harm taken. I just did this out of habit since I am used to pushing tag = just works in the other repos.

I don't think anyone is really using this outside of pekko/play/akka so its not too much harm but yes its something to take into account in the future

**Comment by mdedetrich** [comment]
Also I am more laissez-faire about the community plugins (rightly or wrongly), I have a very different attitude to projects such as Pekko (as you probably already know the release process there is incredibly strict).

**Comment by mkurz** [comment]
Publishing failed: https://github.com/sbt/sbt-pull-request-validator/actions/runs/7681336394/job/20934605470#step:9:116
The `-SNAPSHOT` suffix here indicates that the working directory got dirty during that process to sbt-dynver appends that... (?)

**Comment by mdedetrich** [comment]
> Publishing failed: https://github.com/sbt/sbt-pull-request-validator/actions/runs/7681336394/job/20934605470#step:9:116 The `-SNAPSHOT` suffix here indicates that the working directory got dirty during that process to sbt-dynver appends that... (?)

Thanks, I think that there may be another reason as well (I vaguely remember something similar happening to a repo some time back). Will do some digging

Also just deleted the 2.0.0 release notes

**Comment by mkurz** [comment]
Another problem:
```
2024-01-28 00:09:52.509Z error [SonatypeClient]     Failed: pom-staging, failureMessage:Invalid POM: /com/github/sbt/sbt-pull-request-validator_2.12_1.0/2.0.0/sbt-pull-request-validator-2.0.0.pom: Developer information missing  - (SonatypeClient.scala:384)
````
Needs something like [this](https://github.com/sbt/sbt-osgi/blob/main/build.sbt#L89).
